### ISSUE TITLE
When Rebalance finishes, where did you reset offsets

### ISSUE THREAD

**Issue by xianzhen** [avast/kafka-tests#1]
Hi.
I found this issue:
[KAFA-2978](https://issues.apache.org/jira/browse/KAFKA-2978)
you said  fetched & consumed offsets  are reseted when rebalance finished.
But i haven't see such code in your test project or kafka. Cloud you point it out?

**Comment by mixalturek** [comment]
Hi, the comment https://issues.apache.org/jira/browse/KAFKA-2978?focusedCommentId=15051920&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15051920 was written by Jason Gustafson, he is Kafka developer. He describes there internals of Kafka consumer when auto offset commit is enabled, so this comment is fully unrelated to any code in this repository.

If you have auto offset commit disabled you have to manage the offsets by yourself. See these methods in consumer API:
- consumer.subscribe(), variant with rebalance callback
- consumer.committed()
- consumer.seek()
- consumer.commitSync()
